<a href="https://colab.research.google.com/github/UltraGigaHero/EU_M_Math/blob/main/Chap05_Ex_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import numpy.random as random
import scipy as sp

sample_multi_array_data2 = np.arange(16).reshape(4,4)

print('元のデータ：',sample_multi_array_data2)
print('すべでの要素の平方根',np.sqrt(sample_multi_array_data2))

元のデータ： [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
すべでの要素の平方根 [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739 3.87298335]]
