<a href="https://colab.research.google.com/github/UltraGigaHero/EU_M_Math/blob/main/Chap05_Ex_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import numpy.random as random
import scipy as sp

sample_multi_array_data2 = np.arange(16).reshape(4,4)

print('元のデータ：',sample_multi_array_data2)
print('最小値：',sample_multi_array_data2.min())
print('最大値：',sample_multi_array_data2.max())
print('平均：',sample_multi_array_data2.mean())
print('合計：',sample_multi_array_data2.sum())

元のデータ： [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
最小値： 0
最大値： 15
平均： 7.5
合計： 120
