<a href="https://colab.research.google.com/github/UltraGigaHero/EU_M_Math/blob/main/Chap05_Ex_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import numpy.random as random
import scipy as sp

sample_multi_array_data2 = np.arange(16).reshape(4,4)

print(sample_multi_array_data2)

print('対角',np.diag(sample_multi_array_data2))
print('対角成分の和',np.trace(sample_multi_array_data2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
対角 [ 0  5 10 15]
対角成分の和 30
