<a href="https://colab.research.google.com/github/UltraGigaHero/EU_M_Math/blob/main/Chap05_Ex_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import scipy as sp

A = np.identity(3)
print(A)
A[0,:] = 1
A[:,0] = 1
A[0,0] = 3
b = np.ones(3)

(LU,piv) = sp.linalg.lu_factor(A)
L = np.identity(3) + np.tril(LU,-1)
U = np.triu(LU)
P =np.identity(3)[piv]

x = sp.linalg.lu_solve((LU,piv),b)

print('LU分解の結果:',x)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
LU分解の結果: [-1.  2.  2.]
