<a href="https://colab.research.google.com/github/UltraGigaHero/EU_M_Math/blob/main/Chap02_Ex_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

array1 = np.zeros((5,5)) + 3

array2 = np.dot(array1, array1)

print(array1)
print(array2)


[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
